#!/bin/sh -e

usage() {
	printf '%s\n' "usage: ${0##*/} [--file|--word] pattern" \
	              "       ${0##*/} -h|--help" 1>&2
}

fmt() {
	{ vis-menu -b || :; } |
		awk -v "s=$1" '{ printf "%s", substr($0, length(s)+1) }'
}

esc() {
	echo "$1" | sed 's|[])}^$.*{([]|\\&|g'
}

case "$1" in
--file)
	dir="$(dirname "$2")"
	base="$(basename "$2")"
	if [ -z "${2##*/}" ] && [ "$base" = "." ]; then
		base="" # special case don't ask
	fi
	find "$dir" 2>/dev/null | awk -v "s=$2" -v "dir=$dir" -v "base=$base" '
		BEGIN { i = length(dir)+2; n = length(base); }
		!x[$0]++ && length($0) >= i+n && substr($0, i, n) == base { print s substr($0, i+n) }
	' | fmt "$2"
	;;
-h|--help)
	usage
	;;
--word)
	tr -c '[:alnum:]_' '\n' | awk -v "s=$2" '
		!/^$/ &&
		!x[$0]++ &&
		substr($0, 1, length(s)) == s &&
		length($0) > length(s)
	' | fmt "$2"
	;;
-*|'')
	usage
	exit 1
	;;
*)
	re="$(esc "$1")"
	shift
	grep "$re" "$@" |
		fmt "$2"
	;;
esac
