#!/bin/sh -e

usage() {
	printf '%s\n' "usage: ${0##*/} [--file|--word] pattern" \
	              "       ${0##*/} -h|--help" 1>&2
}

fn() {
	awk -v "s=$1" -v "n=$2" '!x[$0]++ && substr($0, n+1, length(s)) == s { print substr($0, 3) }' |
		{ vis-menu -b || :; } |
		awk -v "s=$1" '{ printf "%s", substr($0, length(s)+1) }'
}

case "$1" in
--file)
	s="./$2"
	find "${s%%/*}" | head -n 10000 | while read -r f; do
		if [ -d "$f" ]; then
			echo "$f/"
		else
			echo "$f"
		fi
	done | fn "${s#./}" 2
	;;
-h|--help)
	usage
	;;
--word)
	fn "$2"
	;;
-*|'')
	usage
	exit 1
	;;
*)
	fn "$1"
	;;
esac
