-- Eight-color scheme
-- light
return {{
	DEFAULT = 'back:white,fore:black',
	NOTHING = 'back:white',
	CLASS = 'fore:yellow,bold',
	COMMENT = 'fore:blue,bold',
	CONSTANT = 'fore:cyan,bold',
	DEFINITION = 'fore:blue,bold',
	ERROR = 'fore:red,italics',
	FUNCTION = 'fore:blue,bold',
	KEYWORD = 'fore:yellow,bold',
	LABEL = 'fore:green,bold',
	NUMBER = 'fore:red,bold',
	OPERATOR = 'fore:cyan,bold',
	REGEX = 'fore:green,bold',
	STRING = 'fore:red,bold',
	PREPROCESSOR = 'fore:magenta,bold',
	TAG = 'fore:red,bold',
	TYPE = 'fore:green,bold',
	VARIABLE = 'fore:blue,bold',
	WHITESPACE = '',
	EMBEDDED = 'back:blue,bold',
	IDENTIFIER = 'fore:black',
	LINENUMBER = 'fore:black',
	LINENUMBER_CURSOR = 'fore:black',
	CURSOR = 'reverse',
	CURSOR_PRIMARY = 'reverse,fore:yellow',
	CURSOR_LINE = 'underlined',
	COLOR_COLUMN = 'back:red',
	SELECTION = 'back:black',
	STATUS = 'reverse',
	STATUS_FOCUSED = 'reverse,bold',
	SEPARATOR = 'back:white',
	INFO = 'fore:default,back:default,bold',
	EOF = '',
}}
